package com.yahoo.ycsb.db; /**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.Set;
import java.util.HashSet;
import java.util.Collections;
import java.util.BitSet;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.facebook.thrift.*;
import com.facebook.thrift.async.*;
import com.facebook.thrift.meta_data.*;
import com.facebook.thrift.server.*;
import com.facebook.thrift.transport.*;
import com.facebook.thrift.protocol.*;

@SuppressWarnings({ "unused", "serial" })
public class QueryTarget implements TBase, java.io.Serializable, Cloneable, Comparable<QueryTarget> {
  private static final TStruct STRUCT_DESC = new TStruct("QueryTarget");
  private static final TField TARGET_FIELD_DESC = new TField("target", TType.STRING, (short)1);
  private static final TField REF_ID_FIELD_DESC = new TField("refId", TType.STRING, (short)2);

  public String target;
  public String refId;
  public static final int TARGET = 1;
  public static final int REFID = 2;
  public static boolean DEFAULT_PRETTY_PRINT = true;

  // isset id assignments

  public static final Map<Integer, FieldMetaData> metaDataMap;
  static {
    Map<Integer, FieldMetaData> tmpMetaDataMap = new HashMap<Integer, FieldMetaData>();
    tmpMetaDataMap.put(TARGET, new FieldMetaData("target", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.STRING)));
    tmpMetaDataMap.put(REFID, new FieldMetaData("refId", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMetaDataMap);
  }

  static {
    FieldMetaData.addStructMetaDataMap(QueryTarget.class, metaDataMap);
  }

  public QueryTarget() {
  }

  public QueryTarget(
    String target,
    String refId)
  {
    this();
    this.target = target;
    this.refId = refId;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public QueryTarget(QueryTarget other) {
    if (other.isSetTarget()) {
      this.target = TBaseHelper.deepCopy(other.target);
    }
    if (other.isSetRefId()) {
      this.refId = TBaseHelper.deepCopy(other.refId);
    }
  }

  public QueryTarget deepCopy() {
    return new QueryTarget(this);
  }

  @Deprecated
  public QueryTarget clone() {
    return new QueryTarget(this);
  }

  public String  getTarget() {
    return this.target;
  }

  public QueryTarget setTarget(String target) {
    this.target = target;
    return this;
  }

  public void unsetTarget() {
    this.target = null;
  }

  // Returns true if field target is set (has been assigned a value) and false otherwise
  public boolean isSetTarget() {
    return this.target != null;
  }

  public void setTargetIsSet(boolean value) {
    if (!value) {
      this.target = null;
    }
  }

  public String  getRefId() {
    return this.refId;
  }

  public QueryTarget setRefId(String refId) {
    this.refId = refId;
    return this;
  }

  public void unsetRefId() {
    this.refId = null;
  }

  // Returns true if field refId is set (has been assigned a value) and false otherwise
  public boolean isSetRefId() {
    return this.refId != null;
  }

  public void setRefIdIsSet(boolean value) {
    if (!value) {
      this.refId = null;
    }
  }

  public void setFieldValue(int fieldID, Object value) {
    switch (fieldID) {
    case TARGET:
      if (value == null) {
        unsetTarget();
      } else {
        setTarget((String)value);
      }
      break;

    case REFID:
      if (value == null) {
        unsetRefId();
      } else {
        setRefId((String)value);
      }
      break;

    default:
      throw new IllegalArgumentException("Field " + fieldID + " doesn't exist!");
    }
  }

  public Object getFieldValue(int fieldID) {
    switch (fieldID) {
    case TARGET:
      return getTarget();

    case REFID:
      return getRefId();

    default:
      throw new IllegalArgumentException("Field " + fieldID + " doesn't exist!");
    }
  }

  // Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise
  public boolean isSet(int fieldID) {
    switch (fieldID) {
    case TARGET:
      return isSetTarget();
    case REFID:
      return isSetRefId();
    default:
      throw new IllegalArgumentException("Field " + fieldID + " doesn't exist!");
    }
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof QueryTarget)
      return this.equals((QueryTarget)that);
    return false;
  }

  public boolean equals(QueryTarget that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_target = true && this.isSetTarget();
    boolean that_present_target = true && that.isSetTarget();
    if (this_present_target || that_present_target) {
      if (!(this_present_target && that_present_target))
        return false;
      if (!TBaseHelper.equalsNobinary(this.target, that.target))
        return false;
    }

    boolean this_present_refId = true && this.isSetRefId();
    boolean that_present_refId = true && that.isSetRefId();
    if (this_present_refId || that_present_refId) {
      if (!(this_present_refId && that_present_refId))
        return false;
      if (!TBaseHelper.equalsNobinary(this.refId, that.refId))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(QueryTarget other) {
    if (other == null) {
      // See java.lang.Comparable docs
      throw new NullPointerException();
    }

    if (other == this) {
      return 0;
    }
    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetTarget()).compareTo(other.isSetTarget());
    if (lastComparison != 0) {
      return lastComparison;
    }
    lastComparison = TBaseHelper.compareTo(target, other.target);
    if (lastComparison != 0) {
      return lastComparison;
    }
    lastComparison = Boolean.valueOf(isSetRefId()).compareTo(other.isSetRefId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    lastComparison = TBaseHelper.compareTo(refId, other.refId);
    if (lastComparison != 0) {
      return lastComparison;
    }
    return 0;
  }

  public void read(TProtocol iprot) throws TException {
    TField field;
    iprot.readStructBegin(metaDataMap);
    while (true)
    {
      field = iprot.readFieldBegin();
      if (field.type == TType.STOP) { 
        break;
      }
      switch (field.id)
      {
        case TARGET:
          if (field.type == TType.STRING) {
            this.target = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case REFID:
          if (field.type == TType.STRING) {
            this.refId = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        default:
          TProtocolUtil.skip(iprot, field.type);
          break;
      }
      iprot.readFieldEnd();
    }
    iprot.readStructEnd();


    // check for required fields of primitive type, which can't be checked in the validate method
    validate();
  }

  public void write(TProtocol oprot) throws TException {
    validate();

    oprot.writeStructBegin(STRUCT_DESC);
    if (this.target != null) {
      oprot.writeFieldBegin(TARGET_FIELD_DESC);
      oprot.writeString(this.target);
      oprot.writeFieldEnd();
    }
    if (this.refId != null) {
      oprot.writeFieldBegin(REF_ID_FIELD_DESC);
      oprot.writeString(this.refId);
      oprot.writeFieldEnd();
    }
    oprot.writeFieldStop();
    oprot.writeStructEnd();
  }

  @Override
  public String toString() {
    return toString(DEFAULT_PRETTY_PRINT);
  }

  @Override
  public String toString(boolean prettyPrint) {
    return toString(1, prettyPrint);
  }

  @Override
  public String toString(int indent, boolean prettyPrint) {
    String indentStr = prettyPrint ? TBaseHelper.getIndentedString(indent) : "";
    String newLine = prettyPrint ? "\n" : "";
String space = prettyPrint ? " " : "";
    StringBuilder sb = new StringBuilder("QueryTarget");
    sb.append(space);
    sb.append("(");
    sb.append(newLine);
    boolean first = true;

    sb.append(indentStr);
    sb.append("target");
    sb.append(space);
    sb.append(":").append(space);
    if (this. getTarget() == null) {
      sb.append("null");
    } else {
      sb.append(TBaseHelper.toString(this. getTarget(), indent + 1, prettyPrint));
    }
    first = false;
    if (!first) sb.append("," + newLine);
    sb.append(indentStr);
    sb.append("refId");
    sb.append(space);
    sb.append(":").append(space);
    if (this. getRefId() == null) {
      sb.append("null");
    } else {
      sb.append(TBaseHelper.toString(this. getRefId(), indent + 1, prettyPrint));
    }
    first = false;
    sb.append(newLine + TBaseHelper.reduceIndent(indentStr));
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws TException {
    // check for required fields
    // check that fields of type enum have valid values
  }

}

